# Generated by Django 3.1.4 on 2020-12-17 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Post', max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('sport', 'Sport'), ('travel', 'Travel'), ('culture', 'Culture'), ('politics', 'Politics'), ('lifestyle', 'Lifestyle'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('books', 'Books'), ('reviews', 'Reviews'), ('contactus', 'Contactus')], default='home', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='blog.author')),
            ],
        ),
    ]
