# Generated by Django 3.1.4 on 2020-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('sport', 'Sport'), ('travel', 'Travel'), ('culture', 'Culture'), ('politics', 'Politics'), ('lifestyle', 'Lifestyle'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('books', 'Books'), ('reviews', 'Reviews'), ('contactus', 'Contactus')], default='home', max_length=50),
        ),
    ]
