# Generated by Django 3.1.4 on 2020-12-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201215_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='month',
        ),
    ]
